site_name: Venkateswara Reddy Somu
copyright: Venkateswara Reddy S

site_description: "My Project."

repo_name: venkatsomu/venkatdocs.github.io

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "black"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  generator: false

nav:
    - Home: index.md
    - OIC: 
      - oic/oic-basic-questions.md
      - oic/oic-interview-questions.md
      - oic/oic-Realtime-questions.md
      - oic/naming-standars.md
    - OIC Components:
      - fusion/fusion-interview-questions.md
    
copyright: Copyright &copy; 2023 Venkateswara Reddy S

